name: Destroy - Infra Dia 1

on:
  workflow_dispatch:
    inputs:
      confirm:
        description: 'Digite "destroy" para confirmar a destruicao dos recursos'
        required: true

env:
  TF_VAR_mysql_admin_password: ${{ secrets.MYSQL_ADMIN_PASSWORD }}

jobs:
  terraform-destroy:
    if: github.event.inputs.confirm == 'destroy'
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: infra

    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Terraform Init
        run: |
          export ARM_SUBSCRIPTION_ID=$(az account show --query id -o tsv)
          terraform init -upgrade

      - name: Terraform Destroy
        run: |
          export ARM_SUBSCRIPTION_ID=$(az account show --query id -o tsv)
          terraform destroy -auto-approve
